//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdoc.Parsers {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mdoc.Parsers.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 強調表示&apos;**&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoldError {
            get {
                return ResourceManager.GetString("BoldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロック要素エラー: [:contents-all:N-M]のフォーマットが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentsAllError {
            get {
                return ResourceManager.GetString("ContentsAllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロック要素エラー: [:contents:N-M]のフォーマットが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentsError {
            get {
                return ResourceManager.GetString("ContentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 強調表示&apos;*&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmphasisError {
            get {
                return ResourceManager.GetString("EmphasisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 取り消し線表示&apos;&lt;del&gt;&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlDelError {
            get {
                return ResourceManager.GetString("HtmlDelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 強調表示&apos;&lt;em&gt;&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlEmError {
            get {
                return ResourceManager.GetString("HtmlEmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 細目表示&apos;&lt;small&gt;&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlSmallError {
            get {
                return ResourceManager.GetString("HtmlSmallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 強い強調表示&apos;&lt;strong&gt;&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlStrongError {
            get {
                return ResourceManager.GetString("HtmlStrongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 下付き文字表示&apos;&lt;sub&gt;&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlSubError {
            get {
                return ResourceManager.GetString("HtmlSubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: 上付き文字表示&apos;&lt;sup&gt;&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlSupError {
            get {
                return ResourceManager.GetString("HtmlSupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: ハイパーリンク&apos;[&apos;のフォーマットが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HyperlinkError {
            get {
                return ResourceManager.GetString("HyperlinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: コード表示&apos;`&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InlineCodeError {
            get {
                return ResourceManager.GetString("InlineCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インライン要素エラー: ハイパーリンク&apos;[[&apos;が閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UriHyperlinkError {
            get {
                return ResourceManager.GetString("UriHyperlinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLスキーマ&apos;javascript:&apos;は使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlCheckJavascript {
            get {
                return ResourceManager.GetString("UrlCheckJavascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLスキーマ&apos;vbscript:&apos;は使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlCheckVbScript {
            get {
                return ResourceManager.GetString("UrlCheckVbScript", resourceCulture);
            }
        }
    }
}
